- name: Run nh os switch
  hosts: all
  gather_facts: false
  vars:
    nh_config_path: '"$HOME/.config/nix-config"'
  tasks:
    - name: Update nix-config using git
      ansible.builtin.command:
        cmd: git -C "{{ nh_config_path }}" pull

    - name: Execute nh os switch
      ansible.builtin.command:
        cmd: nh os switch {{ nh_config_path }}
      register: nh_result
      failed_when: nh_result.rc != 0

    - name: Show nh os switch stdout
      ansible.builtin.debug:
        msg: "{{ nh_result.stdout_lines | default(['<no stdout>']) }}"
