- name: Check tailscale status
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if tailscaled systemd unit exists
      ansible.builtin.stat:
        path: /etc/systemd/system/tailscaled.service
      register: tailscaled_unit

    - name: Query tailscaled state
      ansible.builtin.systemd:
        name: tailscaled
        state: started
      register: tailscale_service
      when: tailscaled_unit.stat.exists

    - name: Report tailscale service state
      ansible.builtin.debug:
        msg: >-
          Tailscale {{ 'running' if tailscale_service.status.ActiveState == 'active' else 'NOT running' }}
      when: tailscaled_unit.stat.exists

    - name: Collect tailscale IPv4
      ansible.builtin.command: tailscale ip -4
      register: tailscale_ip
      ignore_errors: true
      when: tailscaled_unit.stat.exists

    - name: Show tailscale IP status
      ansible.builtin.debug:
        msg: >-
          {{ tailscale_ip.stdout if tailscale_ip.rc == 0 else 'Tailscale status failed or Tailscale is not running' }}
      when: tailscaled_unit.stat.exists

    - name: Tailscale unit missing notice
      ansible.builtin.debug:
        msg: Tailscale systemd unit not found
      when: not tailscaled_unit.stat.exists
